services:
  fastapi_backend_project_job:
    image: arturscibor/praca.server.arturscibor.pl:latest
    ports:
      - "3000:3000"
    env_file:
      - env/prod.env
    volumes:
      - .:/app
    networks:
      - project_job
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  project_job:
    driver: overlay
