services:
  fastapi_backend_project_job:
    build:
      context: .
      dockerfile: dockerfiles/prod.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - env/prod.env
    volumes:
      - .:/app

  nginx_backend:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "3000:80"
    depends_on:
      - fastapi_backend_project_job
    volumes:
      - ./dockerfiles/nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - project_job

networks:
  project_job:
    driver: bridge