version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=artek.scibor@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-cert:/letsencrypt
    networks:
      - traefik-public
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.praca.rule=Host(`praca.server.arturscibor.pl`)"
        - "traefik.http.routers.praca.entrypoints=websecure"
        - "traefik.http.routers.praca.tls.certresolver=myresolver"
        - "traefik.http.services.praca.loadbalancer.server.port=8080"

volumes:
  traefik-cert:

networks:
  traefik-public:
    external: true
