"""init

Revision ID: 9507ebdeec64
Revises: 
Create Date: 2026-09-15 13:07:14.885605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9507ebdeec64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_work_condition_changes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('norm_hours', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_work_condition_changes_id'), 'calendar_work_condition_changes', ['id'], unique=False)
    op.create_table('calendar_work_days',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('norm_hours', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_calendar_work_days_id'), 'calendar_work_days', ['id'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('application', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_application'), 'contact_messages', ['application'], unique=False)
    op.create_table('files_nodes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['files_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_files_nodes_parent_name')
    )
    op.create_index(op.f('ix_files_nodes_parent_id'), 'files_nodes', ['parent_id'], unique=False)
    op.create_table('keyscalculatorpatryk',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('income_tax', sa.Float(), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('inpost_parcel_locker', sa.Float(), nullable=True),
    sa.Column('inpost_courier', sa.Float(), nullable=True),
    sa.Column('inpost_cash_of_delivery_courier', sa.Float(), nullable=True),
    sa.Column('dpd', sa.Float(), nullable=True),
    sa.Column('allegro_matt', sa.Float(), nullable=True),
    sa.Column('without_smart', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('namesoverdue',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outstandingmoney',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('id_name', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rentals_apartments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rentals_beneficiaries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rentals_billing_periods',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('electricity_bill_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electricity_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('electricity_rate_is_manual', sa.Boolean(), nullable=False),
    sa.Column('water_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_month')
    )
    op.create_table('rentals_cost_types',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('charge_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rentals_tenants',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('node_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('parent_file_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.Enum('PHOTO', 'VIDEO', 'GIF', 'AUDIO', name='file_type'), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('s3_prefix', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CONFIRMED', name='file_status'), nullable=False),
    sa.Column('multipart_upload_id', sa.String(length=1024), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('uploaded_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['files_nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index('ix_files_file_type', 'files', ['file_type'], unique=False)
    op.create_index(op.f('ix_files_node_id'), 'files', ['node_id'], unique=False)
    op.create_index(op.f('ix_files_parent_file_id'), 'files', ['parent_file_id'], unique=False)
    op.create_index('ix_files_status', 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_table('rentals_allocation_rules',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('apartment_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('cost_type_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['rentals_apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['rentals_beneficiaries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cost_type_id'], ['rentals_cost_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_allocation_rules_apartment_id'), 'rentals_allocation_rules', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_rentals_allocation_rules_beneficiary_id'), 'rentals_allocation_rules', ['beneficiary_id'], unique=False)
    op.create_table('rentals_apartment_costs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('apartment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cost_type_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['rentals_apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cost_type_id'], ['rentals_cost_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_apartment_costs_apartment_id'), 'rentals_apartment_costs', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_rentals_apartment_costs_cost_type_id'), 'rentals_apartment_costs', ['cost_type_id'], unique=False)
    op.create_table('rentals_beneficiary_settlements',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('period_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('beneficiary_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['rentals_beneficiaries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['rentals_billing_periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'beneficiary_id', name='uq_rentals_beneficiary_settlements_period_beneficiary')
    )
    op.create_index(op.f('ix_rentals_beneficiary_settlements_beneficiary_id'), 'rentals_beneficiary_settlements', ['beneficiary_id'], unique=False)
    op.create_index(op.f('ix_rentals_beneficiary_settlements_period_id'), 'rentals_beneficiary_settlements', ['period_id'], unique=False)
    op.create_table('rentals_meters',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('apartment_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['rentals_apartments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_meters_apartment_id'), 'rentals_meters', ['apartment_id'], unique=False)
    op.create_table('rentals_tenancies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('apartment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('persons_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['rentals_apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['rentals_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_tenancies_apartment_id'), 'rentals_tenancies', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_rentals_tenancies_tenant_id'), 'rentals_tenancies', ['tenant_id'], unique=False)
    op.create_table('rentals_meter_readings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('period_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('meter_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('previous_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('error_correction', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['rentals_meters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['rentals_billing_periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'meter_id', name='uq_rentals_meter_readings_period_meter')
    )
    op.create_index(op.f('ix_rentals_meter_readings_meter_id'), 'rentals_meter_readings', ['meter_id'], unique=False)
    op.create_index(op.f('ix_rentals_meter_readings_period_id'), 'rentals_meter_readings', ['period_id'], unique=False)
    op.create_table('rentals_settlements',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('period_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('apartment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenancy_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('electricity_consumption', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('electricity_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('water_consumption', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('water_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_media_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['rentals_apartments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['rentals_billing_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenancy_id'], ['rentals_tenancies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'apartment_id', name='uq_rentals_settlements_period_apartment')
    )
    op.create_index(op.f('ix_rentals_settlements_apartment_id'), 'rentals_settlements', ['apartment_id'], unique=False)
    op.create_index(op.f('ix_rentals_settlements_period_id'), 'rentals_settlements', ['period_id'], unique=False)
    op.create_table('rentals_beneficiary_settlement_items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('beneficiary_settlement_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rule_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('settlement_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_settlement_id'], ['rentals_beneficiary_settlements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['rentals_allocation_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['rentals_settlements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_beneficiary_settlement_items_beneficiary_settlement_id'), 'rentals_beneficiary_settlement_items', ['beneficiary_settlement_id'], unique=False)
    op.create_table('rentals_settlement_items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('settlement_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cost_type_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cost_type_id'], ['rentals_cost_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['rentals_settlements.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rentals_settlement_items_settlement_id'), 'rentals_settlement_items', ['settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_settlement_items_settlement_id'), table_name='rentals_settlement_items')
    op.drop_table('rentals_settlement_items')
    op.drop_index(op.f('ix_rentals_beneficiary_settlement_items_beneficiary_settlement_id'), table_name='rentals_beneficiary_settlement_items')
    op.drop_table('rentals_beneficiary_settlement_items')
    op.drop_index(op.f('ix_rentals_settlements_period_id'), table_name='rentals_settlements')
    op.drop_index(op.f('ix_rentals_settlements_apartment_id'), table_name='rentals_settlements')
    op.drop_table('rentals_settlements')
    op.drop_index(op.f('ix_rentals_meter_readings_period_id'), table_name='rentals_meter_readings')
    op.drop_index(op.f('ix_rentals_meter_readings_meter_id'), table_name='rentals_meter_readings')
    op.drop_table('rentals_meter_readings')
    op.drop_index(op.f('ix_rentals_tenancies_tenant_id'), table_name='rentals_tenancies')
    op.drop_index(op.f('ix_rentals_tenancies_apartment_id'), table_name='rentals_tenancies')
    op.drop_table('rentals_tenancies')
    op.drop_index(op.f('ix_rentals_meters_apartment_id'), table_name='rentals_meters')
    op.drop_table('rentals_meters')
    op.drop_index(op.f('ix_rentals_beneficiary_settlements_period_id'), table_name='rentals_beneficiary_settlements')
    op.drop_index(op.f('ix_rentals_beneficiary_settlements_beneficiary_id'), table_name='rentals_beneficiary_settlements')
    op.drop_table('rentals_beneficiary_settlements')
    op.drop_index(op.f('ix_rentals_apartment_costs_cost_type_id'), table_name='rentals_apartment_costs')
    op.drop_index(op.f('ix_rentals_apartment_costs_apartment_id'), table_name='rentals_apartment_costs')
    op.drop_table('rentals_apartment_costs')
    op.drop_index(op.f('ix_rentals_allocation_rules_beneficiary_id'), table_name='rentals_allocation_rules')
    op.drop_index(op.f('ix_rentals_allocation_rules_apartment_id'), table_name='rentals_allocation_rules')
    op.drop_table('rentals_allocation_rules')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index('ix_files_status', table_name='files')
    op.drop_index(op.f('ix_files_parent_file_id'), table_name='files')
    op.drop_index(op.f('ix_files_node_id'), table_name='files')
    op.drop_index('ix_files_file_type', table_name='files')
    op.drop_table('files')
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('rentals_tenants')
    op.drop_table('rentals_cost_types')
    op.drop_table('rentals_billing_periods')
    op.drop_table('rentals_beneficiaries')
    op.drop_table('rentals_apartments')
    op.drop_table('outstandingmoney')
    op.drop_table('namesoverdue')
    op.drop_table('logs')
    op.drop_table('keyscalculatorpatryk')
    op.drop_index(op.f('ix_files_nodes_parent_id'), table_name='files_nodes')
    op.drop_table('files_nodes')
    op.drop_index(op.f('ix_contact_messages_application'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_calendar_work_days_id'), table_name='calendar_work_days')
    op.drop_table('calendar_work_days')
    op.drop_index(op.f('ix_calendar_work_condition_changes_id'), table_name='calendar_work_condition_changes')
    op.drop_table('calendar_work_condition_changes')
    # ### end Alembic commands ###
