"""init

Revision ID: a672c8dfa01d
Revises: 
Create Date: 2026-07-08 23:21:52.823724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a672c8dfa01d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_work_condition_changes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('norm_hours', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_work_condition_changes_id'), 'calendar_work_condition_changes', ['id'], unique=False)
    op.create_table('calendar_work_days',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('norm_hours', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_calendar_work_days_id'), 'calendar_work_days', ['id'], unique=False)
    op.create_table('keyscalculatorpatryk',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('income_tax', sa.Float(), nullable=True),
    sa.Column('vat', sa.Float(), nullable=True),
    sa.Column('inpost_parcel_locker', sa.Float(), nullable=True),
    sa.Column('inpost_courier', sa.Float(), nullable=True),
    sa.Column('inpost_cash_of_delivery_courier', sa.Float(), nullable=True),
    sa.Column('dpd', sa.Float(), nullable=True),
    sa.Column('allegro_matt', sa.Float(), nullable=True),
    sa.Column('without_smart', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('namesoverdue',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outstandingmoney',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('id_name', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('outstandingmoney')
    op.drop_table('namesoverdue')
    op.drop_table('logs')
    op.drop_table('keyscalculatorpatryk')
    op.drop_index(op.f('ix_calendar_work_days_id'), table_name='calendar_work_days')
    op.drop_table('calendar_work_days')
    op.drop_index(op.f('ix_calendar_work_condition_changes_id'), table_name='calendar_work_condition_changes')
    op.drop_table('calendar_work_condition_changes')
    # ### end Alembic commands ###
