name: Runner

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/run_ci.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  cd:
    needs: ci
    uses: ./.github/workflows/run_cd.yml
    secrets:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      HOST_NAME: ${{ secrets.HOST_NAME }}
      HOST_IP: ${{ secrets.HOST_IP }}
      HOST_NAME_SSH: ${{ secrets.HOST_NAME_SSH }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  report:
    needs: [ci, cd]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong..."
          echo "${{ toJSON(github) }}"
